version: '3.3'
services:
  micro-dockerhub-hook:
    image: etops/micro-dockerhub-hook
    # build: .
    ports:
      - "3999:3000"
    env_file: docker.env
    volumes:
      - ../scripts:/src/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../stacks/:/srv/ # stacks directory
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.role == manager]