version: '3.3'
services:
  micro-dockerhub-hook:
    image: etops/micro-dockerhub-hook
    # build: .
    ports:
      - "3000:3000"
    env_file: docker.env
    volumes:
      - ./scripts:/src/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/srv/
